### ISSUE TITLE
ModuleNotFoundError: No module named 'Errors'

### ISSUE THREAD

**Issue by TongCHEN779** [PavelTrutman/SDP#1]
Hi, I've successfully installed the package polyopt according to the instruction on your webpage. But when I enter Python and import polyopt, I got the following error message:

>>> import polyopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tong.chen\polyopt\polyopt\__init__.py", line 3, in <module>
    from .SDPSolver import SDPSolver
  File "C:\Users\tong.chen\polyopt\polyopt\SDPSolver.py", line 6, in <module>
    import gnuplot as gp
  File "C:\Users\tong.chen\AppData\Local\Continuum\anaconda3\lib\site-packages\gnuplot\__init__.py", line 164, in <module>
    from gnuplot.gp import GnuplotOpts, GnuplotProcess, test_persist
  File "C:\Users\tong.chen\AppData\Local\Continuum\anaconda3\lib\site-packages\gnuplot\gp.py", line 31, in <module>
    from gnuplot.gp_win32 import GnuplotOpts, GnuplotProcess, test_persist
  File "C:\Users\tong.chen\AppData\Local\Continuum\anaconda3\lib\site-packages\gnuplot\gp_win32.py", line 12, in <module>
    import Errors
ModuleNotFoundError: No module named 'Errors'

Could someone help me fix this issue please?

Thanks in advance!

**Comment by PavelTrutman** [comment]
Hi,
that seems to be a problem of the Gnuplot package on Windowns platform. I am using Unix so it is bit difficult to debug it.

I have updated the Gnuplot package, see https://github.com/PavelTrutman/gnuplot.py-py3k/commit/faf5ff204e8d05b3a174d5dbaf8d228ddd6022b9. Can you please verify it with the new version?
